version: '3.1'

services:
  localstack:
    container_name: "localstack-awscd"
    image: localstack/localstack:v12-stable
    network_mode: bridge
    privileged: true
    ports:
      - "4566:4566"
    environment:
      - SERVICES=apigateway,cloudwatch,dynamodb,iam,lambda,kinesis,logs,s3,sns,sts
      - DATA_DIR=/tmp/localstack
      - LAMBDA_EXECUTOR=docker-reuse
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_EXECUTION_ENV=True
    volumes:
      - "./volume/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"