version: '3.1'

services:
  localstack:
    container_name: "localstack-awscd"
    image: localstack/localstack:v12-stable
    network_mode: bridge
    privileged: true
    ports:
      - "4566:4566"
    environment:
      - SERVICES=
      - DATA_DIR=/tmp/localstack
      - LAMBDA_EXECUTOR=docker-reuse
      # - LAMBDA_REMOTE_DOCKER=false
      # - LAMBDA_REMOVE_CONTAINERS=false
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_EXECUTION_ENV=True
    volumes:
      - "./volume/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"