version: '3.1'

services:
  localstack:
    container_name: "localstack-awscd"
    image: localstack/localstack-full
    network_mode: bridge
    privileged: true
    ports:
      - "4566:4566"
      - "8080:8080"
    environment:
      - SERVICES=
      - DATA_DIR=/tmp/localstack
      - PORT_WEB_UI=8080
      - LAMBDA_EXECUTOR=docker-reuse
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_EXECUTION_ENV=True
    volumes:
      - "./volume/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"